### ISSUE TITLE
Click on System.Windows.Controls.MenuItem

### ISSUE THREAD

**Issue by Denys2211** [WPF-Pilot/WpfPilot#5]
**When I try click on menu Item I get exception:** 

System.InvalidOperationException: An error response was received from the app.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at WpfPilot.AppDriverPayload.ControlHooks.PatchMenuItemHandleMouseUp.Prefix(MenuItem __instance, Object[] __args) in C:\code\WpfPilot\WpfPilot\AppDriverPayload\ControlHooks.cs:line 147
   at System.Windows.Controls.MenuItem.HandleMouseUp_Patch1(MenuItem this, MouseButtonEventArgs e)
   at System.Windows.Controls.MenuItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at WpfPilot.Utility.ReflectionUtility.FindAndInvokeBestMatch(IReadOnlyList`1 methods, Object target, Object[] args) in C:\code\WpfPilot\WpfPilot\Utility\ReflectionUtility.cs:line 14
   at WpfPilot.AppDriverPayload.Commands.ClickCommand.DoClick(RoutedEvent routedEvent, UIElement source, MouseButton mouseButton, IReadOnlyList`1 targets) in C:\code\WpfPilot\WpfPilot\AppDriverPayload\Commands\ClickCommand.cs:line 76
   at WpfPilot.AppDriverPayload.Commands.ClickCommand.Process(Command command, TreeItem appRoot) in C:\code\WpfPilot\WpfPilot\AppDriverPayload\Commands\ClickCommand.cs:line 54
   at WpfPilot.AppDriverPayload.AppDriverPayload.<ProcessCommand>d__2.MoveNext() in C:\code\WpfPilot\WpfPilot\AppDriverPayload\AppDriverPayload.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at WpfPilot.AppDriverPayload.AppDriverPayload.<>c__DisplayClass1_0.<<CommandLoop>b__0>d.MoveNext() in C:\code\WpfPilot\WpfPilot\AppDriverPayload\AppDriverPayload.cs:line 82

 **Stack Trace:** 

     NamedPipeClient.GetResponse(Object command) line 89
     Element.DoClick(String mouseButton) line 487
     BaseGridListTests.MoveToGridList() line 16
     GridListTests.TestFiltering() line 16

**Repro steps:**

   1) AppDriver.GetElement(x => x["Header"] == "Base").Click();

   2) AppDriver.GetElement(x => x["Header"] == "GridList").Click();  //get exception 

**Environment:** 

   .Net Framework  4.8
   x64
   WpfPilot v1.0.1

**Comment by ELanning** [comment]
I believe this shouldn't be difficult to fix. I can likely get a fix out within the next few days.
Sorry for the inconvenience and thanks for the report and comprehensive info.

**Comment by ELanning** [comment]
This has been fixed in this [commit](https://github.com/WPF-Pilot/WpfPilot/commit/092ae0eaf6df00be19341107dddf217b0c1a339c) and should be available in version 1.0.2 on nuget as soon as nuget verifies the package in an hour or so.
